// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trip.proto

package trip

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PreviewTripRequest struct {
	UserID               string      `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	StartLocation        *Coordinate `protobuf:"bytes,2,opt,name=startLocation,proto3" json:"startLocation,omitempty"`
	EndLocation          *Coordinate `protobuf:"bytes,3,opt,name=endLocation,proto3" json:"endLocation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PreviewTripRequest) Reset()         { *m = PreviewTripRequest{} }
func (m *PreviewTripRequest) String() string { return proto.CompactTextString(m) }
func (*PreviewTripRequest) ProtoMessage()    {}
func (*PreviewTripRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a31f58919dc2e020, []int{0}
}

func (m *PreviewTripRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreviewTripRequest.Unmarshal(m, b)
}
func (m *PreviewTripRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreviewTripRequest.Marshal(b, m, deterministic)
}
func (m *PreviewTripRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreviewTripRequest.Merge(m, src)
}
func (m *PreviewTripRequest) XXX_Size() int {
	return xxx_messageInfo_PreviewTripRequest.Size(m)
}
func (m *PreviewTripRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PreviewTripRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PreviewTripRequest proto.InternalMessageInfo

func (m *PreviewTripRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *PreviewTripRequest) GetStartLocation() *Coordinate {
	if m != nil {
		return m.StartLocation
	}
	return nil
}

func (m *PreviewTripRequest) GetEndLocation() *Coordinate {
	if m != nil {
		return m.EndLocation
	}
	return nil
}

type PreviewTripResponse struct {
	TripID               string      `protobuf:"bytes,1,opt,name=tripID,proto3" json:"tripID,omitempty"`
	Route                *Route      `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	RideFares            []*RideFare `protobuf:"bytes,3,rep,name=rideFares,proto3" json:"rideFares,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PreviewTripResponse) Reset()         { *m = PreviewTripResponse{} }
func (m *PreviewTripResponse) String() string { return proto.CompactTextString(m) }
func (*PreviewTripResponse) ProtoMessage()    {}
func (*PreviewTripResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a31f58919dc2e020, []int{1}
}

func (m *PreviewTripResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreviewTripResponse.Unmarshal(m, b)
}
func (m *PreviewTripResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreviewTripResponse.Marshal(b, m, deterministic)
}
func (m *PreviewTripResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreviewTripResponse.Merge(m, src)
}
func (m *PreviewTripResponse) XXX_Size() int {
	return xxx_messageInfo_PreviewTripResponse.Size(m)
}
func (m *PreviewTripResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PreviewTripResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PreviewTripResponse proto.InternalMessageInfo

func (m *PreviewTripResponse) GetTripID() string {
	if m != nil {
		return m.TripID
	}
	return ""
}

func (m *PreviewTripResponse) GetRoute() *Route {
	if m != nil {
		return m.Route
	}
	return nil
}

func (m *PreviewTripResponse) GetRideFares() []*RideFare {
	if m != nil {
		return m.RideFares
	}
	return nil
}

type Coordinate struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinate) Reset()         { *m = Coordinate{} }
func (m *Coordinate) String() string { return proto.CompactTextString(m) }
func (*Coordinate) ProtoMessage()    {}
func (*Coordinate) Descriptor() ([]byte, []int) {
	return fileDescriptor_a31f58919dc2e020, []int{2}
}

func (m *Coordinate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinate.Unmarshal(m, b)
}
func (m *Coordinate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinate.Marshal(b, m, deterministic)
}
func (m *Coordinate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinate.Merge(m, src)
}
func (m *Coordinate) XXX_Size() int {
	return xxx_messageInfo_Coordinate.Size(m)
}
func (m *Coordinate) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinate.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinate proto.InternalMessageInfo

func (m *Coordinate) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Coordinate) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type Geometry struct {
	Coordinates          []*Coordinate `protobuf:"bytes,1,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Geometry) Reset()         { *m = Geometry{} }
func (m *Geometry) String() string { return proto.CompactTextString(m) }
func (*Geometry) ProtoMessage()    {}
func (*Geometry) Descriptor() ([]byte, []int) {
	return fileDescriptor_a31f58919dc2e020, []int{3}
}

func (m *Geometry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Geometry.Unmarshal(m, b)
}
func (m *Geometry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Geometry.Marshal(b, m, deterministic)
}
func (m *Geometry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Geometry.Merge(m, src)
}
func (m *Geometry) XXX_Size() int {
	return xxx_messageInfo_Geometry.Size(m)
}
func (m *Geometry) XXX_DiscardUnknown() {
	xxx_messageInfo_Geometry.DiscardUnknown(m)
}

var xxx_messageInfo_Geometry proto.InternalMessageInfo

func (m *Geometry) GetCoordinates() []*Coordinate {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

type Route struct {
	Geometry             []*Geometry `protobuf:"bytes,1,rep,name=geometry,proto3" json:"geometry,omitempty"`
	Distance             float64     `protobuf:"fixed64,2,opt,name=distance,proto3" json:"distance,omitempty"`
	Duration             float64     `protobuf:"fixed64,3,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}
func (*Route) Descriptor() ([]byte, []int) {
	return fileDescriptor_a31f58919dc2e020, []int{4}
}

func (m *Route) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route.Unmarshal(m, b)
}
func (m *Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route.Marshal(b, m, deterministic)
}
func (m *Route) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route.Merge(m, src)
}
func (m *Route) XXX_Size() int {
	return xxx_messageInfo_Route.Size(m)
}
func (m *Route) XXX_DiscardUnknown() {
	xxx_messageInfo_Route.DiscardUnknown(m)
}

var xxx_messageInfo_Route proto.InternalMessageInfo

func (m *Route) GetGeometry() []*Geometry {
	if m != nil {
		return m.Geometry
	}
	return nil
}

func (m *Route) GetDistance() float64 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *Route) GetDuration() float64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

type RideFare struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	PackageSlug          string   `protobuf:"bytes,3,opt,name=packageSlug,proto3" json:"packageSlug,omitempty"`
	TotalPriceInCents    float64  `protobuf:"fixed64,4,opt,name=totalPriceInCents,proto3" json:"totalPriceInCents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RideFare) Reset()         { *m = RideFare{} }
func (m *RideFare) String() string { return proto.CompactTextString(m) }
func (*RideFare) ProtoMessage()    {}
func (*RideFare) Descriptor() ([]byte, []int) {
	return fileDescriptor_a31f58919dc2e020, []int{5}
}

func (m *RideFare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RideFare.Unmarshal(m, b)
}
func (m *RideFare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RideFare.Marshal(b, m, deterministic)
}
func (m *RideFare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RideFare.Merge(m, src)
}
func (m *RideFare) XXX_Size() int {
	return xxx_messageInfo_RideFare.Size(m)
}
func (m *RideFare) XXX_DiscardUnknown() {
	xxx_messageInfo_RideFare.DiscardUnknown(m)
}

var xxx_messageInfo_RideFare proto.InternalMessageInfo

func (m *RideFare) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RideFare) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *RideFare) GetPackageSlug() string {
	if m != nil {
		return m.PackageSlug
	}
	return ""
}

func (m *RideFare) GetTotalPriceInCents() float64 {
	if m != nil {
		return m.TotalPriceInCents
	}
	return 0
}

type CreateTripRequest struct {
	RideFareID           string   `protobuf:"bytes,1,opt,name=rideFareID,proto3" json:"rideFareID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTripRequest) Reset()         { *m = CreateTripRequest{} }
func (m *CreateTripRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTripRequest) ProtoMessage()    {}
func (*CreateTripRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a31f58919dc2e020, []int{6}
}

func (m *CreateTripRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTripRequest.Unmarshal(m, b)
}
func (m *CreateTripRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTripRequest.Marshal(b, m, deterministic)
}
func (m *CreateTripRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTripRequest.Merge(m, src)
}
func (m *CreateTripRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTripRequest.Size(m)
}
func (m *CreateTripRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTripRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTripRequest proto.InternalMessageInfo

func (m *CreateTripRequest) GetRideFareID() string {
	if m != nil {
		return m.RideFareID
	}
	return ""
}

func (m *CreateTripRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type CreateTripResponse struct {
	TripID               string   `protobuf:"bytes,1,opt,name=tripID,proto3" json:"tripID,omitempty"`
	Trip                 *Trip    `protobuf:"bytes,2,opt,name=trip,proto3" json:"trip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTripResponse) Reset()         { *m = CreateTripResponse{} }
func (m *CreateTripResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTripResponse) ProtoMessage()    {}
func (*CreateTripResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a31f58919dc2e020, []int{7}
}

func (m *CreateTripResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTripResponse.Unmarshal(m, b)
}
func (m *CreateTripResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTripResponse.Marshal(b, m, deterministic)
}
func (m *CreateTripResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTripResponse.Merge(m, src)
}
func (m *CreateTripResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTripResponse.Size(m)
}
func (m *CreateTripResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTripResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTripResponse proto.InternalMessageInfo

func (m *CreateTripResponse) GetTripID() string {
	if m != nil {
		return m.TripID
	}
	return ""
}

func (m *CreateTripResponse) GetTrip() *Trip {
	if m != nil {
		return m.Trip
	}
	return nil
}

type Trip struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SelectedFare         *RideFare   `protobuf:"bytes,2,opt,name=selectedFare,proto3" json:"selectedFare,omitempty"`
	Route                *Route      `protobuf:"bytes,3,opt,name=route,proto3" json:"route,omitempty"`
	Status               string      `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	UserID               string      `protobuf:"bytes,5,opt,name=userID,proto3" json:"userID,omitempty"`
	Driver               *TripDriver `protobuf:"bytes,6,opt,name=driver,proto3" json:"driver,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Trip) Reset()         { *m = Trip{} }
func (m *Trip) String() string { return proto.CompactTextString(m) }
func (*Trip) ProtoMessage()    {}
func (*Trip) Descriptor() ([]byte, []int) {
	return fileDescriptor_a31f58919dc2e020, []int{8}
}

func (m *Trip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trip.Unmarshal(m, b)
}
func (m *Trip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trip.Marshal(b, m, deterministic)
}
func (m *Trip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trip.Merge(m, src)
}
func (m *Trip) XXX_Size() int {
	return xxx_messageInfo_Trip.Size(m)
}
func (m *Trip) XXX_DiscardUnknown() {
	xxx_messageInfo_Trip.DiscardUnknown(m)
}

var xxx_messageInfo_Trip proto.InternalMessageInfo

func (m *Trip) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Trip) GetSelectedFare() *RideFare {
	if m != nil {
		return m.SelectedFare
	}
	return nil
}

func (m *Trip) GetRoute() *Route {
	if m != nil {
		return m.Route
	}
	return nil
}

func (m *Trip) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Trip) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Trip) GetDriver() *TripDriver {
	if m != nil {
		return m.Driver
	}
	return nil
}

// Static driver object that is used to store the driver information
type TripDriver struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProfilePicture       string   `protobuf:"bytes,3,opt,name=profilePicture,proto3" json:"profilePicture,omitempty"`
	CarPlate             string   `protobuf:"bytes,4,opt,name=carPlate,proto3" json:"carPlate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TripDriver) Reset()         { *m = TripDriver{} }
func (m *TripDriver) String() string { return proto.CompactTextString(m) }
func (*TripDriver) ProtoMessage()    {}
func (*TripDriver) Descriptor() ([]byte, []int) {
	return fileDescriptor_a31f58919dc2e020, []int{9}
}

func (m *TripDriver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TripDriver.Unmarshal(m, b)
}
func (m *TripDriver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TripDriver.Marshal(b, m, deterministic)
}
func (m *TripDriver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TripDriver.Merge(m, src)
}
func (m *TripDriver) XXX_Size() int {
	return xxx_messageInfo_TripDriver.Size(m)
}
func (m *TripDriver) XXX_DiscardUnknown() {
	xxx_messageInfo_TripDriver.DiscardUnknown(m)
}

var xxx_messageInfo_TripDriver proto.InternalMessageInfo

func (m *TripDriver) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TripDriver) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TripDriver) GetProfilePicture() string {
	if m != nil {
		return m.ProfilePicture
	}
	return ""
}

func (m *TripDriver) GetCarPlate() string {
	if m != nil {
		return m.CarPlate
	}
	return ""
}

func init() {
	proto.RegisterType((*PreviewTripRequest)(nil), "trip.PreviewTripRequest")
	proto.RegisterType((*PreviewTripResponse)(nil), "trip.PreviewTripResponse")
	proto.RegisterType((*Coordinate)(nil), "trip.Coordinate")
	proto.RegisterType((*Geometry)(nil), "trip.Geometry")
	proto.RegisterType((*Route)(nil), "trip.Route")
	proto.RegisterType((*RideFare)(nil), "trip.RideFare")
	proto.RegisterType((*CreateTripRequest)(nil), "trip.CreateTripRequest")
	proto.RegisterType((*CreateTripResponse)(nil), "trip.CreateTripResponse")
	proto.RegisterType((*Trip)(nil), "trip.Trip")
	proto.RegisterType((*TripDriver)(nil), "trip.TripDriver")
}

func init() {
	proto.RegisterFile("trip.proto", fileDescriptor_a31f58919dc2e020)
}

var fileDescriptor_a31f58919dc2e020 = []byte{
	// 581 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0x93, 0x34, 0x4a, 0xc6, 0x50, 0xd1, 0x45, 0x0a, 0x26, 0x42, 0x55, 0xf0, 0x01, 0x45,
	0xa8, 0x6a, 0xa5, 0x20, 0x71, 0x41, 0x02, 0xa9, 0xa9, 0x8a, 0x2a, 0x7a, 0x88, 0xb6, 0x9c, 0xb8,
	0x2d, 0xf6, 0x10, 0x56, 0x75, 0xbd, 0x66, 0x77, 0x1c, 0xc4, 0x85, 0x03, 0x9f, 0xc0, 0x89, 0x3f,
	0xe2, 0xb7, 0xd0, 0xae, 0x37, 0xb6, 0x93, 0x34, 0xe2, 0x62, 0x79, 0xe6, 0xcd, 0xcc, 0xbe, 0x9d,
	0x79, 0xb3, 0x00, 0xa4, 0x65, 0x71, 0x5a, 0x68, 0x45, 0x8a, 0xf5, 0xec, 0x7f, 0xfc, 0x27, 0x00,
	0xb6, 0xd0, 0xb8, 0x92, 0xf8, 0xfd, 0xa3, 0x96, 0x05, 0xc7, 0x6f, 0x25, 0x1a, 0x62, 0x23, 0xe8,
	0x97, 0x06, 0xf5, 0xd5, 0x45, 0x14, 0x4c, 0x82, 0xe9, 0x90, 0x7b, 0x8b, 0xbd, 0x86, 0x87, 0x86,
	0x84, 0xa6, 0x6b, 0x95, 0x08, 0x92, 0x2a, 0x8f, 0x3a, 0x93, 0x60, 0x1a, 0xce, 0x1e, 0x9d, 0xba,
	0xc2, 0x73, 0xa5, 0x74, 0x2a, 0x73, 0x41, 0xc8, 0x37, 0xc3, 0xd8, 0x0c, 0x42, 0xcc, 0xd3, 0x3a,
	0xab, 0xbb, 0x27, 0xab, 0x1d, 0x14, 0xff, 0x84, 0xc7, 0x1b, 0xcc, 0x4c, 0xa1, 0x72, 0x83, 0x96,
	0x9a, 0x4d, 0x6b, 0xa8, 0x55, 0x16, 0x7b, 0x0e, 0x07, 0x5a, 0x95, 0x84, 0x9e, 0x52, 0x58, 0x15,
	0xe7, 0xd6, 0xc5, 0x2b, 0x84, 0x9d, 0xc0, 0x50, 0xcb, 0x14, 0x2f, 0x85, 0x46, 0x13, 0x75, 0x27,
	0xdd, 0x69, 0x38, 0x3b, 0xf4, 0x61, 0xde, 0xcd, 0x9b, 0x80, 0xf8, 0x12, 0xa0, 0xa1, 0xc6, 0xc6,
	0x30, 0xc8, 0x04, 0x49, 0x2a, 0x53, 0x74, 0x07, 0x07, 0xbc, 0xb6, 0xd9, 0x33, 0x18, 0x66, 0x2a,
	0x5f, 0x56, 0x60, 0xc7, 0x81, 0x8d, 0x23, 0x7e, 0x0b, 0x83, 0xf7, 0xa8, 0xee, 0x90, 0xf4, 0x0f,
	0xdb, 0x87, 0xa4, 0xae, 0x69, 0xa2, 0xc0, 0x71, 0xb8, 0xa7, 0x0f, 0xad, 0xa0, 0xf8, 0x16, 0x0e,
	0xdc, 0x2d, 0xd8, 0x4b, 0x18, 0x2c, 0x7d, 0x21, 0x9f, 0xe9, 0xd9, 0xaf, 0xcb, 0xf3, 0x1a, 0xb7,
	0x74, 0x53, 0x69, 0x48, 0xe4, 0xc9, 0x9a, 0x51, 0x6d, 0x3b, 0xac, 0xd4, 0xcd, 0x24, 0x2c, 0xe6,
	0xed, 0xf8, 0x57, 0x00, 0x83, 0x75, 0x33, 0xd8, 0x21, 0x74, 0x64, 0xea, 0xdb, 0xdc, 0x91, 0x69,
	0x4b, 0x15, 0x9d, 0x0d, 0x55, 0x4c, 0x20, 0x2c, 0x44, 0x72, 0x2b, 0x96, 0x78, 0x93, 0x95, 0x4b,
	0x57, 0x73, 0xc8, 0xdb, 0x2e, 0x76, 0x02, 0x47, 0xa4, 0x48, 0x64, 0x0b, 0x2d, 0x13, 0xbc, 0xca,
	0xe7, 0x98, 0x93, 0x89, 0x7a, 0xee, 0xec, 0x5d, 0x20, 0xfe, 0x00, 0x47, 0x73, 0x8d, 0x82, 0xb0,
	0x2d, 0xc9, 0x63, 0x80, 0xf5, 0x6c, 0xea, 0xd9, 0xb7, 0x3c, 0xfb, 0xc8, 0xc5, 0xd7, 0xc0, 0xda,
	0xc5, 0xfe, 0xa3, 0xa2, 0x63, 0x70, 0x7b, 0xe1, 0x45, 0x04, 0x55, 0x7f, 0x5d, 0x66, 0xb5, 0x2f,
	0x7f, 0x03, 0xe8, 0x59, 0x73, 0xa7, 0x37, 0x33, 0x78, 0x60, 0x30, 0xc3, 0x84, 0x30, 0xb5, 0x84,
	0x7c, 0x81, 0x6d, 0x79, 0x6d, 0xc4, 0x34, 0x92, 0xed, 0xee, 0x95, 0xec, 0x08, 0xfa, 0x86, 0x04,
	0x95, 0x55, 0xb7, 0x86, 0xdc, 0x5b, 0xad, 0xdb, 0x1e, 0x6c, 0x8c, 0x62, 0x0a, 0xfd, 0x54, 0xcb,
	0x15, 0xea, 0xa8, 0xdf, 0xde, 0x31, 0x4b, 0xf9, 0xc2, 0xf9, 0xb9, 0xc7, 0x63, 0x02, 0x68, 0xbc,
	0x3b, 0xd7, 0x61, 0xd0, 0xcb, 0xc5, 0x1d, 0xfa, 0x5e, 0xba, 0x7f, 0xf6, 0x02, 0x0e, 0x0b, 0xad,
	0xbe, 0xc8, 0x0c, 0x17, 0x32, 0xa1, 0x52, 0xa3, 0x9f, 0xf4, 0x96, 0xd7, 0xea, 0x2b, 0x11, 0x7a,
	0x91, 0x09, 0x42, 0xcf, 0xba, 0xb6, 0x67, 0xbf, 0x03, 0x08, 0xed, 0xb1, 0x37, 0xa8, 0x57, 0x32,
	0x41, 0x76, 0x0e, 0x61, 0x6b, 0xc9, 0x59, 0x54, 0xd1, 0xdd, 0x7d, 0x91, 0xc6, 0x4f, 0xef, 0x41,
	0xfc, 0x2c, 0xdf, 0x01, 0x34, 0x13, 0x66, 0x4f, 0xfc, 0x36, 0x6d, 0x0b, 0x68, 0x1c, 0xed, 0x02,
	0x55, 0x81, 0xf3, 0xe8, 0xd3, 0xc8, 0x7c, 0x15, 0x1a, 0xd3, 0x33, 0xf7, 0x34, 0x9e, 0xd9, 0xb8,
	0x37, 0xf6, 0xf3, 0xb9, 0xef, 0x1c, 0xaf, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x37, 0x92, 0xda,
	0xff, 0x39, 0x05, 0x00, 0x00,
}
