// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trip.proto

package trip

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PreviewTripRequest struct {
	UserID               string      `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	StartLocation        *Coordinate `protobuf:"bytes,2,opt,name=startLocation,proto3" json:"startLocation,omitempty"`
	EndLocation          *Coordinate `protobuf:"bytes,3,opt,name=endLocation,proto3" json:"endLocation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PreviewTripRequest) Reset()         { *m = PreviewTripRequest{} }
func (m *PreviewTripRequest) String() string { return proto.CompactTextString(m) }
func (*PreviewTripRequest) ProtoMessage()    {}
func (*PreviewTripRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a31f58919dc2e020, []int{0}
}

func (m *PreviewTripRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreviewTripRequest.Unmarshal(m, b)
}
func (m *PreviewTripRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreviewTripRequest.Marshal(b, m, deterministic)
}
func (m *PreviewTripRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreviewTripRequest.Merge(m, src)
}
func (m *PreviewTripRequest) XXX_Size() int {
	return xxx_messageInfo_PreviewTripRequest.Size(m)
}
func (m *PreviewTripRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PreviewTripRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PreviewTripRequest proto.InternalMessageInfo

func (m *PreviewTripRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *PreviewTripRequest) GetStartLocation() *Coordinate {
	if m != nil {
		return m.StartLocation
	}
	return nil
}

func (m *PreviewTripRequest) GetEndLocation() *Coordinate {
	if m != nil {
		return m.EndLocation
	}
	return nil
}

type PreviewTripResponse struct {
	TripID               string      `protobuf:"bytes,1,opt,name=tripID,proto3" json:"tripID,omitempty"`
	Route                *Route      `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	RideFares            []*RideFare `protobuf:"bytes,3,rep,name=rideFares,proto3" json:"rideFares,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PreviewTripResponse) Reset()         { *m = PreviewTripResponse{} }
func (m *PreviewTripResponse) String() string { return proto.CompactTextString(m) }
func (*PreviewTripResponse) ProtoMessage()    {}
func (*PreviewTripResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a31f58919dc2e020, []int{1}
}

func (m *PreviewTripResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreviewTripResponse.Unmarshal(m, b)
}
func (m *PreviewTripResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreviewTripResponse.Marshal(b, m, deterministic)
}
func (m *PreviewTripResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreviewTripResponse.Merge(m, src)
}
func (m *PreviewTripResponse) XXX_Size() int {
	return xxx_messageInfo_PreviewTripResponse.Size(m)
}
func (m *PreviewTripResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PreviewTripResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PreviewTripResponse proto.InternalMessageInfo

func (m *PreviewTripResponse) GetTripID() string {
	if m != nil {
		return m.TripID
	}
	return ""
}

func (m *PreviewTripResponse) GetRoute() *Route {
	if m != nil {
		return m.Route
	}
	return nil
}

func (m *PreviewTripResponse) GetRideFares() []*RideFare {
	if m != nil {
		return m.RideFares
	}
	return nil
}

type Coordinate struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinate) Reset()         { *m = Coordinate{} }
func (m *Coordinate) String() string { return proto.CompactTextString(m) }
func (*Coordinate) ProtoMessage()    {}
func (*Coordinate) Descriptor() ([]byte, []int) {
	return fileDescriptor_a31f58919dc2e020, []int{2}
}

func (m *Coordinate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinate.Unmarshal(m, b)
}
func (m *Coordinate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinate.Marshal(b, m, deterministic)
}
func (m *Coordinate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinate.Merge(m, src)
}
func (m *Coordinate) XXX_Size() int {
	return xxx_messageInfo_Coordinate.Size(m)
}
func (m *Coordinate) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinate.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinate proto.InternalMessageInfo

func (m *Coordinate) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Coordinate) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type Geometry struct {
	Coordinates          []*Coordinate `protobuf:"bytes,1,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Geometry) Reset()         { *m = Geometry{} }
func (m *Geometry) String() string { return proto.CompactTextString(m) }
func (*Geometry) ProtoMessage()    {}
func (*Geometry) Descriptor() ([]byte, []int) {
	return fileDescriptor_a31f58919dc2e020, []int{3}
}

func (m *Geometry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Geometry.Unmarshal(m, b)
}
func (m *Geometry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Geometry.Marshal(b, m, deterministic)
}
func (m *Geometry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Geometry.Merge(m, src)
}
func (m *Geometry) XXX_Size() int {
	return xxx_messageInfo_Geometry.Size(m)
}
func (m *Geometry) XXX_DiscardUnknown() {
	xxx_messageInfo_Geometry.DiscardUnknown(m)
}

var xxx_messageInfo_Geometry proto.InternalMessageInfo

func (m *Geometry) GetCoordinates() []*Coordinate {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

type Route struct {
	Geometry             []*Geometry `protobuf:"bytes,1,rep,name=geometry,proto3" json:"geometry,omitempty"`
	Distance             float64     `protobuf:"fixed64,2,opt,name=distance,proto3" json:"distance,omitempty"`
	Duration             float64     `protobuf:"fixed64,3,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}
func (*Route) Descriptor() ([]byte, []int) {
	return fileDescriptor_a31f58919dc2e020, []int{4}
}

func (m *Route) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route.Unmarshal(m, b)
}
func (m *Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route.Marshal(b, m, deterministic)
}
func (m *Route) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route.Merge(m, src)
}
func (m *Route) XXX_Size() int {
	return xxx_messageInfo_Route.Size(m)
}
func (m *Route) XXX_DiscardUnknown() {
	xxx_messageInfo_Route.DiscardUnknown(m)
}

var xxx_messageInfo_Route proto.InternalMessageInfo

func (m *Route) GetGeometry() []*Geometry {
	if m != nil {
		return m.Geometry
	}
	return nil
}

func (m *Route) GetDistance() float64 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *Route) GetDuration() float64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

type RideFare struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	PackageSlug          string   `protobuf:"bytes,3,opt,name=packageSlug,proto3" json:"packageSlug,omitempty"`
	TotalPriceInCents    float64  `protobuf:"fixed64,4,opt,name=totalPriceInCents,proto3" json:"totalPriceInCents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RideFare) Reset()         { *m = RideFare{} }
func (m *RideFare) String() string { return proto.CompactTextString(m) }
func (*RideFare) ProtoMessage()    {}
func (*RideFare) Descriptor() ([]byte, []int) {
	return fileDescriptor_a31f58919dc2e020, []int{5}
}

func (m *RideFare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RideFare.Unmarshal(m, b)
}
func (m *RideFare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RideFare.Marshal(b, m, deterministic)
}
func (m *RideFare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RideFare.Merge(m, src)
}
func (m *RideFare) XXX_Size() int {
	return xxx_messageInfo_RideFare.Size(m)
}
func (m *RideFare) XXX_DiscardUnknown() {
	xxx_messageInfo_RideFare.DiscardUnknown(m)
}

var xxx_messageInfo_RideFare proto.InternalMessageInfo

func (m *RideFare) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RideFare) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *RideFare) GetPackageSlug() string {
	if m != nil {
		return m.PackageSlug
	}
	return ""
}

func (m *RideFare) GetTotalPriceInCents() float64 {
	if m != nil {
		return m.TotalPriceInCents
	}
	return 0
}

func init() {
	proto.RegisterType((*PreviewTripRequest)(nil), "trip.PreviewTripRequest")
	proto.RegisterType((*PreviewTripResponse)(nil), "trip.PreviewTripResponse")
	proto.RegisterType((*Coordinate)(nil), "trip.Coordinate")
	proto.RegisterType((*Geometry)(nil), "trip.Geometry")
	proto.RegisterType((*Route)(nil), "trip.Route")
	proto.RegisterType((*RideFare)(nil), "trip.RideFare")
}

func init() {
	proto.RegisterFile("trip.proto", fileDescriptor_a31f58919dc2e020)
}

var fileDescriptor_a31f58919dc2e020 = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x41, 0x8b, 0xd4, 0x30,
	0x14, 0xa6, 0x9d, 0xdd, 0xa5, 0x7d, 0xc5, 0x45, 0x23, 0x2c, 0x75, 0xf1, 0x50, 0x7b, 0x1a, 0x64,
	0xd9, 0x85, 0x0a, 0x5e, 0x04, 0x0f, 0xbb, 0xb2, 0xb2, 0xe0, 0x61, 0xcc, 0x78, 0xf2, 0x16, 0x9b,
	0x47, 0x0d, 0x53, 0x93, 0x9a, 0xa4, 0x23, 0x5e, 0x3c, 0xf8, 0x2b, 0xfc, 0xb9, 0x92, 0x34, 0xd3,
	0x76, 0x98, 0xd9, 0x4b, 0xe9, 0x7b, 0xdf, 0xf7, 0xbe, 0x7c, 0x79, 0xf9, 0x00, 0xac, 0x16, 0xdd,
	0x75, 0xa7, 0x95, 0x55, 0xe4, 0xc4, 0xfd, 0x97, 0xff, 0x22, 0x20, 0x2b, 0x8d, 0x5b, 0x81, 0xbf,
	0xbe, 0x68, 0xd1, 0x51, 0xfc, 0xd9, 0xa3, 0xb1, 0xe4, 0x02, 0xce, 0x7a, 0x83, 0xfa, 0xe1, 0x43,
	0x1e, 0x15, 0xd1, 0x32, 0xa5, 0xa1, 0x22, 0x6f, 0xe1, 0x89, 0xb1, 0x4c, 0xdb, 0x4f, 0xaa, 0x66,
	0x56, 0x28, 0x99, 0xc7, 0x45, 0xb4, 0xcc, 0xaa, 0xa7, 0xd7, 0x5e, 0xf8, 0x4e, 0x29, 0xcd, 0x85,
	0x64, 0x16, 0xe9, 0x3e, 0x8d, 0x54, 0x90, 0xa1, 0xe4, 0xe3, 0xd4, 0xe2, 0x91, 0xa9, 0x39, 0xa9,
	0xfc, 0x03, 0xcf, 0xf7, 0x9c, 0x99, 0x4e, 0x49, 0x83, 0xce, 0x9a, 0x1b, 0x9b, 0xac, 0x0d, 0x15,
	0x79, 0x05, 0xa7, 0x5a, 0xf5, 0x16, 0x83, 0xa5, 0x6c, 0x10, 0xa7, 0xae, 0x45, 0x07, 0x84, 0x5c,
	0x41, 0xaa, 0x05, 0xc7, 0x7b, 0xa6, 0xd1, 0xe4, 0x8b, 0x62, 0xb1, 0xcc, 0xaa, 0xf3, 0x40, 0x0b,
	0x6d, 0x3a, 0x11, 0xca, 0x7b, 0x80, 0xc9, 0x1a, 0xb9, 0x84, 0xa4, 0x65, 0x56, 0xd8, 0x9e, 0xa3,
	0x3f, 0x38, 0xa2, 0x63, 0x4d, 0x5e, 0x42, 0xda, 0x2a, 0xd9, 0x0c, 0x60, 0xec, 0xc1, 0xa9, 0x51,
	0xbe, 0x87, 0xe4, 0x23, 0xaa, 0x1f, 0x68, 0xf5, 0x6f, 0xb7, 0x87, 0x7a, 0xd4, 0x34, 0x79, 0xe4,
	0x3d, 0x1c, 0xd9, 0xc3, 0x8c, 0x54, 0x6e, 0xe0, 0xd4, 0xdf, 0x82, 0xbc, 0x86, 0xa4, 0x09, 0x42,
	0x61, 0x32, 0xb8, 0xdf, 0xc9, 0xd3, 0x11, 0x77, 0x76, 0xb9, 0x30, 0x96, 0xc9, 0x7a, 0xe7, 0x68,
	0xac, 0x3d, 0xd6, 0xeb, 0xe9, 0x25, 0x1c, 0x16, 0xea, 0xf2, 0x6f, 0x04, 0xc9, 0x6e, 0x19, 0xe4,
	0x1c, 0x62, 0xc1, 0xc3, 0x9a, 0x63, 0xc1, 0x67, 0xa9, 0x88, 0xf7, 0x52, 0x51, 0x40, 0xd6, 0xb1,
	0x7a, 0xc3, 0x1a, 0x5c, 0xb7, 0x7d, 0xe3, 0x35, 0x53, 0x3a, 0x6f, 0x91, 0x2b, 0x78, 0x66, 0x95,
	0x65, 0xed, 0x4a, 0x8b, 0x1a, 0x1f, 0xe4, 0x1d, 0x4a, 0x6b, 0xf2, 0x13, 0x7f, 0xf6, 0x21, 0x50,
	0x7d, 0x86, 0xcc, 0x3d, 0xf9, 0x1a, 0xf5, 0x56, 0xd4, 0x48, 0x6e, 0x21, 0x9b, 0x05, 0x81, 0xe4,
	0xc3, 0xa5, 0x0f, 0x53, 0x7b, 0xf9, 0xe2, 0x08, 0x32, 0xa4, 0xe6, 0x36, 0xff, 0x7a, 0x61, 0xbe,
	0x33, 0x8d, 0xfc, 0xc6, 0xa7, 0xff, 0xc6, 0x11, 0xdf, 0xb9, 0xcf, 0xb7, 0x33, 0xdf, 0x78, 0xf3,
	0x3f, 0x00, 0x00, 0xff, 0xff, 0x62, 0x52, 0x9d, 0x6d, 0x1c, 0x03, 0x00, 0x00,
}
