// Code generated by protoc-gen-go. DO NOT EDIT.
// source: driver.proto

package driver

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterDriverRequest struct {
	DriverID             string   `protobuf:"bytes,1,opt,name=driverID,proto3" json:"driverID,omitempty"`
	PackageSlug          string   `protobuf:"bytes,2,opt,name=packageSlug,proto3" json:"packageSlug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterDriverRequest) Reset()         { *m = RegisterDriverRequest{} }
func (m *RegisterDriverRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterDriverRequest) ProtoMessage()    {}
func (*RegisterDriverRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_521003751d596b5e, []int{0}
}

func (m *RegisterDriverRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterDriverRequest.Unmarshal(m, b)
}
func (m *RegisterDriverRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterDriverRequest.Marshal(b, m, deterministic)
}
func (m *RegisterDriverRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterDriverRequest.Merge(m, src)
}
func (m *RegisterDriverRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterDriverRequest.Size(m)
}
func (m *RegisterDriverRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterDriverRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterDriverRequest proto.InternalMessageInfo

func (m *RegisterDriverRequest) GetDriverID() string {
	if m != nil {
		return m.DriverID
	}
	return ""
}

func (m *RegisterDriverRequest) GetPackageSlug() string {
	if m != nil {
		return m.PackageSlug
	}
	return ""
}

type RegisterDriverResponse struct {
	Driver               *Driver  `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterDriverResponse) Reset()         { *m = RegisterDriverResponse{} }
func (m *RegisterDriverResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterDriverResponse) ProtoMessage()    {}
func (*RegisterDriverResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_521003751d596b5e, []int{1}
}

func (m *RegisterDriverResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterDriverResponse.Unmarshal(m, b)
}
func (m *RegisterDriverResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterDriverResponse.Marshal(b, m, deterministic)
}
func (m *RegisterDriverResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterDriverResponse.Merge(m, src)
}
func (m *RegisterDriverResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterDriverResponse.Size(m)
}
func (m *RegisterDriverResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterDriverResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterDriverResponse proto.InternalMessageInfo

func (m *RegisterDriverResponse) GetDriver() *Driver {
	if m != nil {
		return m.Driver
	}
	return nil
}

type Driver struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProfilePicture       string    `protobuf:"bytes,3,opt,name=profilePicture,proto3" json:"profilePicture,omitempty"`
	CarPlate             string    `protobuf:"bytes,4,opt,name=carPlate,proto3" json:"carPlate,omitempty"`
	Geohash              string    `protobuf:"bytes,5,opt,name=geohash,proto3" json:"geohash,omitempty"`
	PackageSlug          string    `protobuf:"bytes,6,opt,name=packageSlug,proto3" json:"packageSlug,omitempty"`
	Location             *Location `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Driver) Reset()         { *m = Driver{} }
func (m *Driver) String() string { return proto.CompactTextString(m) }
func (*Driver) ProtoMessage()    {}
func (*Driver) Descriptor() ([]byte, []int) {
	return fileDescriptor_521003751d596b5e, []int{2}
}

func (m *Driver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Driver.Unmarshal(m, b)
}
func (m *Driver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Driver.Marshal(b, m, deterministic)
}
func (m *Driver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Driver.Merge(m, src)
}
func (m *Driver) XXX_Size() int {
	return xxx_messageInfo_Driver.Size(m)
}
func (m *Driver) XXX_DiscardUnknown() {
	xxx_messageInfo_Driver.DiscardUnknown(m)
}

var xxx_messageInfo_Driver proto.InternalMessageInfo

func (m *Driver) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Driver) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Driver) GetProfilePicture() string {
	if m != nil {
		return m.ProfilePicture
	}
	return ""
}

func (m *Driver) GetCarPlate() string {
	if m != nil {
		return m.CarPlate
	}
	return ""
}

func (m *Driver) GetGeohash() string {
	if m != nil {
		return m.Geohash
	}
	return ""
}

func (m *Driver) GetPackageSlug() string {
	if m != nil {
		return m.PackageSlug
	}
	return ""
}

func (m *Driver) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type Location struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_521003751d596b5e, []int{3}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Location) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func init() {
	proto.RegisterType((*RegisterDriverRequest)(nil), "driver.RegisterDriverRequest")
	proto.RegisterType((*RegisterDriverResponse)(nil), "driver.RegisterDriverResponse")
	proto.RegisterType((*Driver)(nil), "driver.Driver")
	proto.RegisterType((*Location)(nil), "driver.Location")
}

func init() {
	proto.RegisterFile("driver.proto", fileDescriptor_521003751d596b5e)
}

var fileDescriptor_521003751d596b5e = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x4f, 0x4b, 0xc3, 0x30,
	0x14, 0xa7, 0x75, 0x76, 0xdb, 0x9b, 0x96, 0xf1, 0x40, 0x09, 0x63, 0xca, 0xd8, 0x61, 0x78, 0x90,
	0x0d, 0xe6, 0xd1, 0x8b, 0xc8, 0x2e, 0x82, 0xe0, 0xec, 0xd8, 0xc5, 0x5b, 0x6c, 0x9f, 0x5d, 0xb0,
	0x36, 0x35, 0x4d, 0xf7, 0xc5, 0xfc, 0x36, 0x7e, 0x1a, 0x59, 0x92, 0x4e, 0x9d, 0x7a, 0xf3, 0xd4,
	0xfe, 0xfe, 0xf0, 0xf2, 0xfb, 0xe5, 0x05, 0x0e, 0x12, 0x25, 0xd6, 0xa4, 0xc6, 0x85, 0x92, 0x5a,
	0x62, 0x60, 0xd1, 0x70, 0x09, 0x47, 0x11, 0xa5, 0xa2, 0xd4, 0xa4, 0x66, 0x86, 0x89, 0xe8, 0xb5,
	0xa2, 0x52, 0x63, 0x0f, 0x5a, 0xd6, 0x72, 0x33, 0x63, 0xde, 0xc0, 0x3b, 0x6b, 0x47, 0x5b, 0x8c,
	0x03, 0xe8, 0x14, 0x3c, 0x7e, 0xe6, 0x29, 0x2d, 0xb2, 0x2a, 0x65, 0xbe, 0x91, 0xbf, 0x52, 0xc3,
	0x2b, 0x38, 0xde, 0x1d, 0x5b, 0x16, 0x32, 0x2f, 0x09, 0x47, 0xe0, 0x8e, 0x36, 0x53, 0x3b, 0xd3,
	0x70, 0xec, 0x72, 0x39, 0x5f, 0x1d, 0xec, 0xdd, 0x83, 0xc0, 0x52, 0x18, 0x82, 0x2f, 0x12, 0x17,
	0xc2, 0x17, 0x09, 0x22, 0x34, 0x72, 0xfe, 0x42, 0xee, 0x5c, 0xf3, 0x8f, 0x23, 0x08, 0x0b, 0x25,
	0x9f, 0x44, 0x46, 0x73, 0x11, 0xeb, 0x4a, 0x11, 0xdb, 0x33, 0xea, 0x0e, 0xbb, 0xa9, 0x15, 0x73,
	0x35, 0xcf, 0xb8, 0x26, 0xd6, 0xb0, 0xb5, 0x6a, 0x8c, 0x0c, 0x9a, 0x29, 0xc9, 0x15, 0x2f, 0x57,
	0x6c, 0xdf, 0x48, 0x35, 0xdc, 0x2d, 0x1c, 0xfc, 0x28, 0x8c, 0xe7, 0xd0, 0xca, 0x64, 0xcc, 0xb5,
	0x90, 0x39, 0x6b, 0x9a, 0x62, 0xdd, 0xba, 0xd8, 0xad, 0xe3, 0xa3, 0xad, 0x63, 0x38, 0x83, 0x56,
	0xcd, 0x6e, 0x12, 0x65, 0x5c, 0x0b, 0x5d, 0x25, 0x64, 0x3a, 0x7a, 0xd1, 0x16, 0x63, 0x1f, 0xda,
	0x99, 0xcc, 0x53, 0x2b, 0xfa, 0x46, 0xfc, 0x24, 0xa6, 0x6f, 0x1e, 0x1c, 0xda, 0x2b, 0x5a, 0x90,
	0x5a, 0x8b, 0x98, 0xf0, 0x0e, 0xc2, 0xef, 0xd7, 0x8e, 0x27, 0x75, 0x8a, 0x5f, 0xb7, 0xdc, 0x3b,
	0xfd, 0x4b, 0x76, 0xdb, 0xba, 0x87, 0xee, 0x32, 0x57, 0xff, 0x39, 0xf2, 0xba, 0xff, 0xd0, 0x2b,
	0x57, 0x5c, 0x51, 0x32, 0x31, 0x2f, 0x71, 0x62, 0xdd, 0x97, 0xf6, 0xf3, 0x18, 0x18, 0xf2, 0xe2,
	0x23, 0x00, 0x00, 0xff, 0xff, 0x10, 0x6c, 0xfe, 0xe2, 0xae, 0x02, 0x00, 0x00,
}
